# Generated by Django 3.2.16 on 2024-05-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_favorites_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagrecipe',
            old_name='tag_name',
            new_name='name',
        ),
    ]
