# Generated by Django 4.1.3 on 2024-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
